# Generated by Django 5.0.4 on 2024-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
