# Generated by Django 5.0.4 on 2024-04-20 19:54

import django.db.models.deletion
from django.db import migrations, models

from grades.models import Grade


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_grade_subject'),
    ]

    def cleardb(apps, scheme_editor):
        Grade.objects.all().delete()

    operations = [
        migrations.RunPython(cleardb),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grades.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subject'),
        ),
    ]
